{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "52484e5f_dce541e4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2022-06-09T07:40:34Z",
      "side": 1,
      "message": "recheck",
      "revId": "1ec1fad720a1aecea2bb7baba143e50813fd167e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2e5adaca_bc67bde6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1017140
      },
      "writtenOn": "2022-06-15T16:09:18Z",
      "side": 1,
      "message": "this is not reflecting the instackenv.json file correctly for UEFI boot:\n\n    \"nodes\": [\n        {\n      \"name\": \"compute-0\",\n                  \"ports\": [{\"address\": \"52:54:00:0a:89:0d\", \"local_link_connection\": {\"switch_id\": \"52:54:00:00:00:00\", \"port_id\": \"1\"}}],\n            \"cpu\": \"2\",\n      \"memory\": \"8192\",\n      \"disk\": \"50\",\n            \"arch\": \"x86_64\",\n              \"pm_addr\": \"172.16.0.28\",\n        \"pm_type\": \"ipmi\",\n        \"pm_user\": \"admin\",\n        \"pm_password\": \"password\",\n        \"pm_port\": \"6230\"\n                  , \"capabilities\":\n        {\n          \"boot_mode\":\"uefi\",\n                      \"profile\":\"compute\"\n                    \"boot_option\":\"local\"\n        }\n        \n        This is not adding \",\" after  \"profile\":\"compute\" and thus introspection is failing:\n        \n        2022-06-15 00:43:12.585 | /usr/lib/python3.9/site-packages/ansible/_vendor/__init__.py:42: UserWarning: One or more Python packages bundled by this ansible-core distribution were already loaded (pyparsing). This may result in undefined behavior.\n2022-06-15 00:43:12.586 |   warnings.warn(\u0027One or more Python packages bundled by this ansible-core distribution were already \u0027\n2022-06-15 00:43:12.588 | Exception occured while running the command\n2022-06-15 00:43:12.589 | Traceback (most recent call last):\n2022-06-15 00:43:12.591 |   File \"/usr/lib/python3.9/site-packages/tripleoclient/command.py\", line 34, in run\n2022-06-15 00:43:12.592 |     super(Command, self).run(parsed_args)\n2022-06-15 00:43:12.594 |   File \"/usr/lib/python3.9/site-packages/osc_lib/command/command.py\", line 39, in run\n2022-06-15 00:43:12.595 |     return super(Command, self).run(parsed_args)\n2022-06-15 00:43:12.597 |   File \"/usr/lib/python3.9/site-packages/cliff/command.py\", line 186, in run\n2022-06-15 00:43:12.598 |     return_code \u003d self.take_action(parsed_args) or 0\n2022-06-15 00:43:12.600 |   File \"/usr/lib/python3.9/site-packages/tripleoclient/v2/overcloud_node.py\", line 96, in take_action\n2022-06-15 00:43:12.601 |     nodes_config \u003d oooutils.parse_env_file(parsed_args.env_file)\n2022-06-15 00:43:12.603 |   File \"/usr/lib/python3.9/site-packages/tripleoclient/utils.py\", line 1520, in parse_env_file\n2022-06-15 00:43:12.604 |     nodes_config \u003d simplejson.load(env_file)\n2022-06-15 00:43:12.606 |   File \"/usr/lib64/python3.9/site-packages/simplejson/__init__.py\", line 467, in load\n2022-06-15 00:43:12.607 |     return loads(fp.read(),\n2022-06-15 00:43:12.609 |   File \"/usr/lib64/python3.9/site-packages/simplejson/__init__.py\", line 525, in loads\n2022-06-15 00:43:12.610 |     return _default_decoder.decode(s)\n2022-06-15 00:43:12.612 |   File \"/usr/lib64/python3.9/site-packages/simplejson/decoder.py\", line 370, in decode\n2022-06-15 00:43:12.613 |     obj, end \u003d self.raw_decode(s)\n2022-06-15 00:43:12.615 |   File \"/usr/lib64/python3.9/site-packages/simplejson/decoder.py\", line 400, in raw_decode\n2022-06-15 00:43:12.616 |     return self.scan_once(s, idx\u003d_w(s, idx).end())\n2022-06-15 00:43:12.618 | simplejson.errors.JSONDecodeError: Expecting \u0027,\u0027 delimiter or \u0027}\u0027: line 19 column 21 (char 585)\n2022-06-15 00:43:12.619 | Expecting \u0027,\u0027 delimiter or \u0027}\u0027: line 19 column 21 (char 585)\n2022-06-15 00:43:12.621 | \n2022-06-15 00:43:12.622 | \n2022-06-15 00:43:12.624 | MSG:\n2022-06-15 00:43:12.625 | \n2022-06-15 00:43:12.627 | non-zero return code\n2022-06-15 00:43:12.628 | \n2022-06-15 00:43:12.630 | NO MORE HOSTS LEFT *************************************************************\n2022-06-15 00:43:12.631 | \n2022-06-15 00:43:12.633 | PLAY RECAP *********************************************************************\n2022-06-15 00:43:12.634 | hypervisor                 : ok\u003d1    changed\u003d0    unreachable\u003d0    failed\u003d0    skipped\u003d0    rescued\u003d0    ignored\u003d0   \n2022-06-15 00:43:12.636 | localhost                  : ok\u003d3    changed\u003d0    unreachable\u003d0    failed\u003d0    skipped\u003d5    rescued\u003d0    ignored\u003d0   \n2022-06-15 00:43:12.637 | undercloud-0               : ok\u003d60   changed\u003d32   unreachable\u003d0    failed\u003d1    skipped\u003d67   rescued\u003d0    ignored\u003d1 ",
      "revId": "1ec1fad720a1aecea2bb7baba143e50813fd167e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "facf8610_03967191",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1006843
      },
      "writtenOn": "2022-06-15T18:17:32Z",
      "side": 1,
      "message": "I\u0027ve created a fix - https://review.gerrithub.io/c/redhat-openstack/infrared/+/539775, feel free to review, thanks.",
      "parentUuid": "2e5adaca_bc67bde6",
      "revId": "1ec1fad720a1aecea2bb7baba143e50813fd167e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ],
  "submitRequirementResults": []
}