{
  "comments": [
    {
      "key": {
        "uuid": "71eaf3a2_8a57f49d",
        "filename": "plugins/tripleo-undercloud/tasks/images/repos.yml",
        "patchSetId": 3
      },
      "lineNbr": 94,
      "author": {
        "id": 1013090
      },
      "writtenOn": "2018-12-25T08:35:53Z",
      "side": 1,
      "message": "If the upload was made in the previous task, you still need to do it again? so the image will be in the root directory and /etc?",
      "range": {
        "startLine": 94,
        "startChar": 0,
        "endLine": 94,
        "endChar": 42
      },
      "revId": "25f4c6dc33f3b21e0283966a8e172044b9a5287a",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "c9bbc111_2f2f1270",
        "filename": "plugins/tripleo-undercloud/tasks/images/repos.yml",
        "patchSetId": 3
      },
      "lineNbr": 94,
      "author": {
        "id": 1014336
      },
      "writtenOn": "2018-12-25T11:47:20Z",
      "side": 1,
      "message": "My previous patch which introduced the option to upload custom undercloud repos isn\u0027t stored in merge_base_url var, it\u0027s a file which is transferred to the tmp_oc_repos_dir, when the patch that introduced disabling custom repositories it didn\u0027t take into account my way of uploading.\n\nRegardless, a refactoring should be done which enables the repositories instead of uploading them a second time.",
      "parentUuid": "71eaf3a2_8a57f49d",
      "range": {
        "startLine": 94,
        "startChar": 0,
        "endLine": 94,
        "endChar": 42
      },
      "revId": "25f4c6dc33f3b21e0283966a8e172044b9a5287a",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}