{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "85a426c2_d1863689",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2022-08-03T10:09:57Z",
      "side": 1,
      "message": "Weird, on patchset 4:\n\n$ ansible-playbook -i /home/fhubik/.infrared/.workspaces/workspace/hosts \nplugins/tripleo-overcloud/docker_after_workaround.yml\n# 0\n\n$ python -m testtools.run  tempest.api.object_storage.test_container_acl_negative.ObjectACLsNegativeTest.test_write_object_without_using_creds\n\ntempest.lib.exceptions.Unauthorized: Unauthorized\nDetails: b\u0027AccessDenied\u0027\nRan 1 test in 6.606s\nFAILED (failures\u003d1)",
      "revId": "a9bf253aa5e0371ef8b7102a05d49006a342d793",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}