{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "49bc1572_354900fd",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 22
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2021-12-10T14:09:30Z",
      "side": 1,
      "message": "rebased the whole chain (since child change has rebase conflict)",
      "revId": "eb5907ec2062ba74c7f704824fc1e2a49f78184c",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "075dce37_b61653d4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 22
      },
      "lineNbr": 0,
      "author": {
        "id": 1005097
      },
      "writtenOn": "2021-12-10T14:11:33Z",
      "side": 1,
      "message": "Still testing... Problem above persist.",
      "revId": "eb5907ec2062ba74c7f704824fc1e2a49f78184c",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "5af1b40f_a4f331b0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 22
      },
      "lineNbr": 0,
      "author": {
        "id": 1018946
      },
      "writtenOn": "2021-12-10T14:47:28Z",
      "side": 1,
      "message": "Code is failing when custom name of heat stack(overcloud name) is used with following message:\nInventory file not found in working directory: /home/stack/overcloud-deploy/overcloud/tripleo-ansible-inventory.yaml. It should have been created by \u0027openstack overcloud node provision\u0027\n\nI set stack name to qe-Cloud-0 and files were generated in different location.\n[stack@undercloud-0 ~]$ ls overcloud-deploy/qe-Cloud-0/\ninventory-network-config.yaml   tripleo-qe-Cloud-0-baremetal-deployment.yaml\ntripleo-ansible-inventory.yaml  tripleo-qe-Cloud-0-virtual-ips.yaml\n",
      "revId": "eb5907ec2062ba74c7f704824fc1e2a49f78184c",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}